"""Stable ORM import surface backed by bounded-context declaration modules.

New domain code should import its declarations from ``models_auth``,
``models_catalog``, ``models_indexing``, or ``models_operations``.  This module
remains the public compatibility surface for migrations and established
repository imports; it deliberately contains no ORM declarations of its own.
"""

from app.state.model_base import (
    Base,
    IndexingRunStatus,
    IndexVersionStatus,
    IngestionRunStatus,
    JDBCDriverRegistryEntry,
    JobStatus,
    MessageRole,
    ScheduleAttemptStatus,
    SourceType,
    SourceVersionStatus,
    TimestampMixin,
    UserRole,
)
from app.state.models_auth import (
    Answer,
    AnswerSource,
    APIKey,
    AuditEvent,
    Conversation,
    InferenceJob,
    Message,
    RefreshSession,
    Tenant,
    User,
)
from app.state.models_catalog import (
    ContentBlob,
    DocumentChunk,
    IngestionRun,
    KnowledgeBase,
    KnowledgeBaseSource,
    KnowledgeSource,
    NormalizedDocument,
    SourceObject,
    SourceVersion,
)
from app.state.models_indexing import (
    ChunkEmbedding,
    EmbeddingModelVersion,
    IndexingEvent,
    IndexingRun,
    KnowledgeIndexEntry,
    KnowledgeIndexVersion,
)
from app.state.models_operations import (
    AnswerFeedback,
    ModelDefinition,
    PromptTemplate,
    RetentionPolicy,
    ScheduleAttempt,
    SourceSchedule,
)

__all__ = [
    "Base",
    "MessageRole",
    "JobStatus",
    "UserRole",
    "SourceType",
    "SourceVersionStatus",
    "IngestionRunStatus",
    "IndexVersionStatus",
    "IndexingRunStatus",
    "ScheduleAttemptStatus",
    "JDBCDriverRegistryEntry",
    "TimestampMixin",
    "Tenant",
    "User",
    "Conversation",
    "Message",
    "InferenceJob",
    "Answer",
    "AnswerSource",
    "RefreshSession",
    "APIKey",
    "AuditEvent",
    "KnowledgeBase",
    "KnowledgeSource",
    "KnowledgeBaseSource",
    "SourceVersion",
    "SourceObject",
    "IngestionRun",
    "ContentBlob",
    "NormalizedDocument",
    "DocumentChunk",
    "EmbeddingModelVersion",
    "KnowledgeIndexVersion",
    "ChunkEmbedding",
    "KnowledgeIndexEntry",
    "IndexingRun",
    "IndexingEvent",
    "SourceSchedule",
    "ScheduleAttempt",
    "RetentionPolicy",
    "ModelDefinition",
    "PromptTemplate",
    "AnswerFeedback",
]
