import { expect, test } from '@playwright/test'

test('login shell is keyboard accessible', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'RAG Assistant' })).toBeVisible()
  await page.keyboard.press('Tab')
  await expect(page.locator('input[name=username]')).toBeFocused()
})

test('owner flow logs in, administers a typed source, streams a cited answer and logs out', async ({ page }) => {
  const posted: string[] = []
  await page.route('**/*', async (route) => {
    const request = route.request(); const url = new URL(request.url()); const path = url.pathname
    if (!path.startsWith('/v1') && path !== '/ask/stream') return route.continue()
    posted.push(`${request.method()} ${path}`)
    const fulfill = (body: unknown, status = 200) => route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(body) })
    if (path === '/v1/setup/status') return fulfill({ required: false, setup_available: false, token_required: false, current_step: 'complete', onboarding_complete: true, config_version: 1 })
    if (path === '/v1/auth/login') return fulfill({ access_token: 'access' })
    if (path === '/v1/auth/me') return fulfill({ user_id: 'u1', tenant_id: 't1', username: 'owner', role: 'admin' })
    if (path === '/v1/knowledge-bases' || path === '/v1/admin/knowledge-bases') return fulfill([{ id: 'kb1', name: 'Product', is_enabled: true }])
    if (path === '/v1/conversations') return fulfill([])
    if (path === '/v1/admin/knowledge-sources' && request.method() === 'POST') return fulfill({ id: 'source1' }, 201)
    if (path === '/v1/admin/knowledge-sources') return fulfill([])
    if (path === '/v1/admin/users' || path === '/v1/api-keys') return fulfill([])
    if (path === '/ask/stream') return route.fulfill({ status: 200, contentType: 'text/event-stream', body: 'id: 1\ndata: {"type":"token","data":"Grounded answer","job_id":"job1"}\n\nid: 2\ndata: {"type":"meta","data":{"retrieved":[{"doc_id":"chunk1","source":"website","title":"Guide","uri":"https://docs.local/guide","score":0.9}]},"job_id":"job1"}\n\nid: 3\ndata: {"type":"completed","data":{},"job_id":"job1"}\n\n' })
    if (path === '/v1/inference-jobs/job1') return fulfill({ job_id: 'job1', conversation_id: 'c1', status: 'completed', answer: { answer_id: 'a1' } })
    if (path === '/v1/auth/logout') return route.fulfill({ status: 204, body: '' })
    return fulfill([])
  })
  await page.goto('/')
  await page.getByLabel('Логин').fill('owner'); await page.getByLabel('Пароль').fill('owner-password'); await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page.getByRole('heading', { name: 'Ассистент' })).toBeVisible()
  await page.getByRole('button', { name: 'Администрирование' }).click(); await page.getByRole('button', { name: 'Подключения' }).click()
  const sourceForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Сохранить подключение' }) })
  await sourceForm.locator('input[name=name]').fill('Local docs'); await sourceForm.getByLabel('Root URL').fill('https://docs.local'); await sourceForm.getByLabel('Разрешённые hosts').fill('docs.local'); await sourceForm.getByRole('button', { name: 'Сохранить подключение' }).click()
  expect(posted).toContain('POST /v1/admin/knowledge-sources')
  await page.getByRole('button', { name: 'Чат' }).click(); await page.getByLabel('Контекст ответа').selectOption('kb1'); await page.getByLabel('Вопрос').fill('How does the product work?'); await page.getByRole('button', { name: 'Отправить' }).click()
  await expect(page.getByText('Grounded answer')).toBeVisible(); await expect(page.getByText('Источники · 1')).toBeVisible()
  await page.locator('.account-button').click(); await expect(page.getByRole('heading', { name: 'Профиль' })).toBeVisible(); await page.getByRole('button', { name: 'Выйти из аккаунта' }).click(); await expect(page.getByRole('heading', { name: 'RAG Assistant' })).toBeVisible()
})

test('first-run wizard creates the owner, configures models and reaches sanitized system status', async ({ page }) => {
  let modelCounter = 0
  const knowledgeBases: Array<{ id: string; name: string; is_enabled: boolean }> = []
  const sources: Array<{ id: string; name: string; source_type: 'website'; config: object; is_enabled: boolean }> = []
  await page.route('**/*', async (route) => {
    const request = route.request(); const path = new URL(request.url()).pathname
    if (!path.startsWith('/v1') && path !== '/ask/stream') return route.continue()
    const fulfill = (body: unknown, status = 200) => route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(body) })
    if (path === '/v1/setup/status') return fulfill({ required: true, setup_available: true, token_required: false, current_step: 'administrator', onboarding_complete: false, config_version: 1 })
    if (path === '/v1/setup/bootstrap') return fulfill({ access_token: 'setup-access' }, 201)
    if (path === '/v1/auth/me') return fulfill({ user_id: 'owner', tenant_id: 'tenant', username: 'admin', role: 'admin' })
    if (path === '/v1/admin/models' && request.method() === 'POST') return fulfill({ id: `model-${++modelCounter}` }, 201)
    if (path.endsWith('/activate') || path.endsWith('/test')) return fulfill({ status: 'ready' })
    if (path === '/v1/setup/progress') return fulfill({ current_step: 'readiness', onboarding_complete: false, config_version: 2 })
    if (path === '/v1/admin/telegram') return fulfill({ enabled: false, config_version: 1 })
    if (path === '/v1/admin/system') return fulfill({ status: 'degraded', components: { api: 'ready', postgresql: 'ready', redis: 'ready', embedding: 'model_loading', generation: 'ready', telegram: 'disabled' } })
    if (path === '/v1/admin/knowledge-bases' && request.method() === 'POST') { knowledgeBases.push({ id: 'kb1', name: 'Local KB', is_enabled: true }); return fulfill(knowledgeBases[0], 201) }
    if (path === '/v1/admin/knowledge-bases' || path === '/v1/knowledge-bases') return fulfill(knowledgeBases)
    if (path === '/v1/admin/knowledge-sources' && request.method() === 'POST') { sources.push({ id: 'source1', name: 'Local docs', source_type: 'website', config: {}, is_enabled: true }); return fulfill(sources[0], 201) }
    if (path === '/v1/admin/knowledge-sources') return fulfill(sources)
    if (path.includes('/sources/source1') && request.method() === 'PUT') return fulfill({ linked: true })
    if (path.endsWith('/refresh')) return fulfill({ id: 'ingestion1', status: 'queued' }, 202)
    if (path.endsWith('/indexing-runs') && request.method() === 'POST') return fulfill({ id: 'indexing1', status: 'queued' }, 202)
    if (path === '/v1/admin/indexing-runs') return fulfill([{ id: 'indexing1', knowledge_base_id: 'kb1', index_version_id: 'index1', status: 'completed', attempt_count: 1, checkpoint: {}, cancel_requested: false }])
    if (path === '/v1/conversations') return fulfill([])
    if (path === '/ask/stream') return route.fulfill({ status: 200, contentType: 'text/event-stream', body: 'id: 1\ndata: {"type":"token","data":"Configured answer","job_id":"job1"}\n\nid: 2\ndata: {"type":"meta","data":{"retrieved":[{"doc_id":"chunk1","source":"website","title":"Local guide","uri":"https://docs.local/guide","score":0.95}]},"job_id":"job1"}\n\nid: 3\ndata: {"type":"completed","data":{},"job_id":"job1"}\n\n' })
    if (path === '/v1/inference-jobs/job1') return fulfill({ job_id: 'job1', conversation_id: 'conversation1', status: 'completed', answer: { answer_id: 'answer1' } })
    return fulfill([])
  })
  await page.goto('/')
  await page.getByLabel('Имя администратора').fill('Owner')
  await page.getByLabel('Пароль', { exact: true }).fill('owner-password-123')
  await page.getByLabel('Повторите пароль').fill('owner-password-123')
  await page.getByRole('button', { name: 'Создать защищённое пространство' }).click()
  await expect(page.getByRole('heading', { name: 'Self-hosted модели' })).toBeVisible()
  await page.getByRole('button', { name: 'Сохранить и проверить модели' }).click()
  await expect(page.getByRole('heading', { name: 'Telegram' })).toBeVisible()
  await page.getByRole('button', { name: 'Продолжить' }).click()
  await page.getByRole('button', { name: 'Проверить сервисы' }).click()
  await expect(page.getByText('model_loading')).toBeVisible()
  await page.getByRole('button', { name: 'Завершить setup и открыть продукт' }).click()
  await expect(page.getByRole('heading', { name: 'Администрирование' })).toBeVisible()
  await page.getByRole('button', { name: 'Подключения' }).click()
  const knowledgeBaseForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Создать базу' }) })
  await knowledgeBaseForm.getByLabel('Название').fill('Local KB')
  await knowledgeBaseForm.getByRole('button', { name: 'Создать базу' }).click()
  const setupSourceForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Сохранить подключение' }) })
  await setupSourceForm.locator('input[name=name]').fill('Local docs')
  await setupSourceForm.getByLabel('Root URL').fill('https://docs.local')
  await setupSourceForm.getByLabel('Разрешённые hosts').fill('docs.local')
  await setupSourceForm.getByRole('button', { name: 'Сохранить подключение' }).click()
  const sourceLinkForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Добавить' }) })
  await sourceLinkForm.getByRole('button', { name: 'Добавить' }).click()
  await page.getByRole('button', { name: 'Проверить и обновить' }).click()
  await page.getByRole('button', { name: 'Индексировать' }).click()
  await expect(page.getByText('completed')).toBeVisible()
  await page.getByRole('button', { name: 'Чат' }).click()
  await page.getByLabel('Контекст ответа').selectOption('kb1')
  await page.getByLabel('Вопрос').fill('Что находится в локальной документации?')
  await page.getByRole('button', { name: 'Отправить' }).click()
  await expect(page.getByText('Configured answer')).toBeVisible()
  await expect(page.getByText('Источники · 1')).toBeVisible()
})
